version: '3.3'

services:
  redis:
    image : redis
    ports: # 바인딩할 포트:내부 포트
      - 6379:6379
    volumes: # 마운트할 볼륨 설정
      - .\redis\store:/data
    networks:
      - network

  server:
    image: madst0614/budget-manager:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${APPLICATION_PROFILE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - network

networks:
  network: